### ISSUE TITLE
playit_agent losing connection

### ISSUE THREAD

**Issue by arosado2895** [PepaonDrugs/playitgg-docker-0.9.3#2]
![image](https://user-images.githubusercontent.com/44014186/219819751-a4d133b9-1e28-42a8-964d-614a2b8460d0.png)

**Comment by arosado2895** [comment]
The issue normally persists after having the playit running for about 4-8 hours. It randomly disconnects and then reconnects. Sometimes it doesn't go back online and I have to end up restarting the container. @PepaonDrugs

**Comment by PepaonDrugs** [comment]
Could you try the same thing with the agent but not inside docker if that also doesnt work the problem is not on my side.

**Comment by JonasCardoso** [comment]
> The issue normally persists after having the playit running for about 4-8 hours. It randomly disconnects and then reconnects. Sometimes it doesn't go back online and I have to end up restarting the container. @PepaonDrugs

i have same problem, any workaround?

**Comment by PepaonDrugs** [comment]
Hey @JonasCardoso 
Thanks for letting me know 
Could you please also try if the same thing  happens when not using Playit as a docker container.

**Comment by JonasCardoso** [comment]
> Hey @JonasCardoso Thanks for letting me know Could you please also try if the same thing happens when not using Playit as a docker container.

yess, i will try

**Comment by JonasCardoso** [comment]
> Hey @JonasCardoso Thanks for letting me know Could you please also try if the same thing happens when not using Playit as a docker container.

Idk, now I've had no problems, I've started via docker and not docker (binary), both down sevice, but the service comes back, I don't know what happened the other time

**Comment by PepaonDrugs** [comment]
Yeah Playit still has some problems i also noticed that i got disconnected sometimes when using it
