### ISSUE TITLE
OMV on Raspberry Pi 3B errors

### ISSUE THREAD

**Issue by CraftoHohenvels** [PepaonDrugs/playitgg-docker-0.9.3#3]
When I use your Docker Compose for ARM to deploy it as a stack in a Portainer instance I get the following error:
`exec /bin/sh: exec format error`

I sadly can't give you more informations as I am not that into Docker and Raspberry Pis

**Comment by PepaonDrugs** [comment]
Are you using a 64bit or a 32bit operating system 

if you dont know try this for 32bit


version: "3"

services:
  playit-docker:
    container_name: "playit-docker"
    image: pepaondrugs/playitgg-docker:v0.9.3-armv7
    volumes:
        - playit-volume:/app
    restart: unless-stopped
volumes:
    playit-volume:
        external: false
