### ISSUE TITLE
Force a specific datacenter?

### ISSUE THREAD

**Issue by Ryuo1** [PepaonDrugs/playitgg-docker-0.9.3#4]
How can I force playit to use a specific datacenter?

**Comment by PepaonDrugs** [comment]
Hey as far as i know it isnt possible i also had some problems with that 
try changing your dns to a standart one like 8.8.8.8

The problem is on playit side because this is just the agent in docker 
you can try to ask them for support at their discord https://discord.com/invite/AXAbujx

**Comment by Ryuo1** [comment]
Maybe by editing the .toml config file I can force it to use a specific datacenter? But I couldn't find out where the config files of the container are located

**Comment by PepaonDrugs** [comment]
Ah okay all the playit files are in /app

**Comment by Ryuo1** [comment]
where is /app

**Comment by Ryuo1** [comment]
Basically I wanted to set it the nearest datacentere but that wasnt possible since ipv6 was disabled from my side. Anyways the issue is not fixed after enabling it.

**Comment by PepaonDrugs** [comment]
The issue is on playit side i cant really do anything
