### ISSUE TITLE
Unable to connect to Playit.gg servers

### ISSUE THREAD

**Issue by arosado2895** [PepaonDrugs/playitgg-docker-0.9.3#5]
![image](https://github.com/PepaonDrugs/playitgg-docker/assets/44014186/2abf3fc2-2777-4d75-a153-13b77d4bb6cb)

Please review the image.  Re-created new container and new agent to connect to Playit.gg servers and after claiming and assigning the host machine playit does not recognize or does not proceed to handshake "control.playit.gg". 

Tested on same and separate machines with the regular .exe and .dmg versions of playit agent 0.9.3 and it connected immediately.

**Comment by PepaonDrugs** [comment]
Hey could you Try to ping control.playit.gg inside the Container

apt-get update && apt-get install -y iputils-ping

ping control.playit.gg


also check the Dns inside the container

apt install nano

nano /etc/resolv.conf

**Comment by arosado2895** [comment]
Issue seems to have corrected itself. It seems like no intervention was needed from the image.
