### ISSUE TITLE
Version Upgrade / Validation (0.9.3 to 0.15.9)

### ISSUE THREAD

**Issue by arosado2895** [PepaonDrugs/playitgg-docker-0.9.3#6]
Hi again, Pepa.

Sorry to bother, I don't know where to contact you other then here. I've observed your docker image is still on v0.9.3 I do see you have a new branch towards v0.15.9 but it hasn't been merged yet as your default branch is set to v0.9.3 I would set it to a main branch since on your docker compose yml it's still pointing to the old version.

Just a heads up.

**Comment by PepaonDrugs** [comment]
Hey yes I tried to merge some of the new versions but I always got an API error from playit not only from the container but also from the official program I will try to merge it again later this day

**Comment by PepaonDrugs** [comment]
Just pushed v0.15.9 for x64 the api error was my fault because my agend limit was reached

Happy to see your results
