### ISSUE TITLE
AMP Servers

### ISSUE THREAD

**Issue by OfficiallyBrown** [PepaonDrugs/playitgg-docker-0.9.3#7]
Not sure if this is really the best place to ask, but I'm trying to use this with AMP by CubeCoders on unraid. I can get servers running and joinable. I have the local address on the playit manager set to what AMP says, but on BattleMetrics and in game (ie Valhiem) it's showing the server is on my personal ip and not the playit one

Any help you could give would be appreciated

**Comment by PepaonDrugs** [comment]
Hey, sorry I cannot help with this. I guess this is probably a config issue with Valheim. You will probably be better off trying your luck in the Playit Discord: https://discord.com/invite/AXAbujx

**Comment by OfficiallyBrown** [comment]
Alright, thanks anyway
